### PR TITLE
Fix cloud partial search url

### LINKED ISSUE #323: Partial search is not working in cloud-enabled site
When searching a cloud-enabled dictionary, `Match whole words` is working opposite of what it was intended.

For example, searching for `naa` without setting `Match whole words` result in no results, `https://www.webonary.org/test-chung?s=naa&search=Search&key=&tax=&search_options_set=1&displayAdvancedSearchName=1&lang=en

Screen Shot 2022-05-13 at 3 01 36 PM

But searching with 'Match whole words' clicked finds the partial word matches, https://www.webonary.org/test-chung?s=naa&search=Search&key=&tax=&search_options_set=1&match_whole_words=1&displayAdvancedSearchName=1&lang=en
Screen Shot 2022-05-13 at 3 04 40 PM

[See https://github.com/sillsdev/webonary/issues/184#issuecomment-1123053687], where it was uncovered.

### PR DESCRIPTION
**Pull request by hanatgit**
Resolves #323

### CODE REVIEW

File: wp-resources/plugins/sil-dictionary-webonary/webonary/Webonary_Cloud.php [hunk 1]
```diff
@@ -370,7 +370,7 @@ public static function searchEntries($posts, WP_Query $query): ?array {
 				[
 					'key' => ['filter' => FILTER_UNSAFE_RAW],
 					'tax' => ['filter' => FILTER_UNSAFE_RAW],
-					'match_whole_words' => ['filter' => FILTER_UNSAFE_RAW, 'options' => ['default' => '1']],
+					'match_whole_words' => ['filter' => FILTER_UNSAFE_RAW, 'options' => ['default' => '0']],
```
Comment (johntseng) [inline wp-resources/plugins/sil-dictionary-webonary/webonary/Webonary_Cloud.php]: Does it matter that the default on the UI is match_whole_words=1? 
image

**Review by johntseng — APPROVED** [review]

File: wp-resources/plugins/sil-dictionary-webonary/webonary/Webonary_Cloud.php (hunk 1 above)
Comment (hanatgit) [reply wp-resources/plugins/sil-dictionary-webonary/webonary/Webonary_Cloud.php]: This says that if `match_whole_words` parameter is not specified in the URL, assume falsy, `'0'`. This matches the current behavior in the PHP side, https://github.com/sillsdev/webonary/blob/437cd8e3bf07fae53411997fed0ba6838f469e95/wp-resources/plugins/sil-dictionary-webonary/include/dictionary-search.php#L71

**Review by phillip-hopper — APPROVED** [review]
LGTM :+1:
