### PR TITLE
Issue-394: fix the language dropdown for cloud projects

### LINKED ISSUE #394: Search widget improvements
1. Alphabetize the items in the Part of Speech dropdown box.
image

2. Add language as a filter to the Advanced Search dialog box. Set All languages as the default. Alphabetize the languages.
image

3. Remove nonsensical message, which only shows when Match whole words is ticked.

image

### PR DESCRIPTION
**Pull request by phillip-hopper**
Resolves #394

### CODE REVIEW

File: wp-resources/plugins/sil-dictionary-webonary/include/searchform_func.php [hunk 1]
```diff
@@ -82,32 +82,40 @@ function webonary_searchform($use_li = false): void
...
-					$language_name = Webonary_Cloud::getLanguageName($lang);
-					$language_dropdown_options .= "<option value='" . $lang . "'" . $selected . ">" . $language_name . "</option>";
+			$other_search_languages = array_filter($dictionary->reversalLanguages, function($lang) use($dictionary) {
+				return $lang->lang != $dictionary->mainLanguage->lang;
+			});
+
+			if (count($other_search_languages)) {
+
+				/** @noinspection HtmlUnknownAttribute */
+				$option_template = '<option value="%s" %s>%s</option>' . PHP_EOL;
```
Comment (johntseng) [inline wp-resources/plugins/sil-dictionary-webonary/include/searchform_func.php:101]: Do we sanitize the language on input? Or is this vulnerable to XSS?

**Review by johntseng — APPROVED** [review]
