### PR TITLE
Issue 44 - Paging not working in search results

### LINKED ISSUE #44: paging does not work after a search is done in Webonary
Page links do display, but each of the pages contain the full search results.

### PR DESCRIPTION
**Pull request by phillip-hopper**
* Update .gitignore
* Fix PHP warnings
* Add LIMIT clause to the `posts_request` filter

### CODE REVIEW

File: wordpress/wp-content/plugins/sil-dictionary-webonary/webonary/Webonary_Utility.php [hunk 1]
```diff
@@ -3,6 +3,12 @@
 
 class Webonary_Utility
 {
+	// TODO: Check if this is reasonable, or should be increased.
+	private const DEFAULT_POSTS_PER_PAGE = 25;
```
Comment (hanatgit) [inline wordpress/wp-content/plugins/sil-dictionary-webonary/webonary/Webonary_Utility.php]: Unfortunately, Webonary is still using PHP 7.0, so this results in an error:

`PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) `

Perhaps a define() or private static?

File: wordpress/wp-content/plugins/sil-dictionary-webonary/include/dictionary-search.php [hunk 2]
```diff
@@ -413,6 +416,25 @@ function replace_default_search_filter($input, $query=null)
...
 
+/**
+ * Hook to override the default page length
+ *
+ * @param string $input
+ * @param WP_Query $query
+ *
+ * @return string
+ */
+function replace_default_search_limits($input, $query=null)
```
Comment (phillip-hopper) [inline wordpress/wp-content/plugins/sil-dictionary-webonary/include/dictionary-search.php]: I ended up using this hook because the paging was being calculated on 10 entries per page, regardless of what the SQL limit was.

**Comment by hanatgit** [comment]
All good! This exposes an existing issue with lack of page links in semantic domain view page. Currently, all entries are shown. With this PR, only the first page is shown. This shortcoming will be resolved in https://github.com/sillsdev/webonary/issues/51. Once this is done, both will be moved to the live server.

**Review by hanatgit — APPROVED** [review]
